# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(617, 377)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 601, 341))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.layoutWidget = QtWidgets.QWidget(self.mainTab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 261, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roomIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.roomIDLabel.setObjectName("roomIDLabel")
        self.horizontalLayout_2.addWidget(self.roomIDLabel)
        self.roomIDinfo = QtWidgets.QLabel(self.layoutWidget)
        self.roomIDinfo.setObjectName("roomIDinfo")
        self.horizontalLayout_2.addWidget(self.roomIDinfo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.courseNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.courseNameLabel.setObjectName("courseNameLabel")
        self.horizontalLayout_3.addWidget(self.courseNameLabel)
        self.courseNameInfo = QtWidgets.QLabel(self.layoutWidget)
        self.courseNameInfo.setObjectName("courseNameInfo")
        self.horizontalLayout_3.addWidget(self.courseNameInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lecturerLabel = QtWidgets.QLabel(self.layoutWidget)
        self.lecturerLabel.setObjectName("lecturerLabel")
        self.horizontalLayout_6.addWidget(self.lecturerLabel)
        self.lecturerInfo = QtWidgets.QLabel(self.layoutWidget)
        self.lecturerInfo.setObjectName("lecturerInfo")
        self.horizontalLayout_6.addWidget(self.lecturerInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.descriptionLabel = QtWidgets.QLabel(self.layoutWidget)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.horizontalLayout_5.addWidget(self.descriptionLabel)
        self.descriptionInfo = QtWidgets.QLabel(self.layoutWidget)
        self.descriptionInfo.setObjectName("descriptionInfo")
        self.horizontalLayout_5.addWidget(self.descriptionInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.currentViewLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentViewLabel.setObjectName("currentViewLabel")
        self.horizontalLayout_4.addWidget(self.currentViewLabel)
        self.currentViewInfo = QtWidgets.QLabel(self.layoutWidget)
        self.currentViewInfo.setObjectName("currentViewInfo")
        self.horizontalLayout_4.addWidget(self.currentViewInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("homeicon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.mainTab, icon, "")
        self.materialsTab = QtWidgets.QWidget()
        self.materialsTab.setObjectName("materialsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.materialsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scroll_area = QtWidgets.QScrollArea(self.materialsTab)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scroll_area)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bookicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.materialsTab, icon1, "")
        self.streamTab = QtWidgets.QWidget()
        self.streamTab.setObjectName("streamTab")
        self.leave_button = QtWidgets.QPushButton(self.streamTab)
        self.leave_button.setGeometry(QtCore.QRect(470, 0, 113, 32))
        self.leave_button.setObjectName("leave_button")
        self.layoutWidget1 = QtWidgets.QWidget(self.streamTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 40, 216, 261))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_browser = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.chat_browser.setObjectName("chat_browser")
        self.verticalLayout_3.addWidget(self.chat_browser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chat_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.chat_edit.setObjectName("chat_edit")
        self.horizontalLayout.addWidget(self.chat_edit)
        self.send_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stream_label = QtWidgets.QLabel(self.streamTab)
        self.stream_label.setGeometry(QtCore.QRect(20, 40, 331, 261))
        self.stream_label.setText("")
        self.stream_label.setObjectName("stream_label")
        self.cover_label = QtWidgets.QLabel(self.streamTab)
        self.cover_label.setGeometry(QtCore.QRect(0, 40, 591, 281))
        self.cover_label.setText("")
        self.cover_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cover_label.setObjectName("cover_label")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("eyeicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.streamTab, icon2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.roomIDLabel.setText(_translate("Form", "Room ID:"))
        self.roomIDinfo.setText(_translate("Form", "-"))
        self.courseNameLabel.setText(_translate("Form", "Course Name: "))
        self.courseNameInfo.setText(_translate("Form", "-"))
        self.lecturerLabel.setText(_translate("Form", "Lecturer: "))
        self.lecturerInfo.setText(_translate("Form", "-"))
        self.descriptionLabel.setText(_translate("Form", "Description:"))
        self.descriptionInfo.setText(_translate("Form", "-"))
        self.currentViewLabel.setText(_translate("Form", "Current Viewers: "))
        self.currentViewInfo.setText(_translate("Form", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("Form", "Main"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.mainTab), _translate("Form", "Main Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.materialsTab), _translate("Form", "Materials"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.materialsTab), _translate("Form", "Materials"))
        self.leave_button.setText(_translate("Form", "Leave Room"))
        self.send_button.setText(_translate("Form", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.streamTab), _translate("Form", "Stream"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.streamTab), _translate("Form", "Watch Stream"))

